Repository YoshithaRathnayake/CALCULATOR-WEBSITE, pull requests merged in 2022-10, with the labels that each got.

#8 Add the topic
  index.html
Labels: hacktoberfest-accepted

#9 Add a sentence
  index.html
Labels: hacktoberfest-accepted

#10 Add the image
  index.html
Labels: hacktoberfest-accepted

#12 Aligned center the topic
  index.html
Labels: hacktoberfest-accepted

#23 Align the image to center
  index.html
Labels: good first issue, hacktoberfest-accepted

#24 Align the paragraph center
  index.html
Labels: good first issue, hacktoberfest-accepted

#25 Updates styles.css by increasing the main title's font size and gave a margin to the title and paragraph
  assets/css/styles.css
Labels: good first issue, hacktoberfest-accepted

#38 Increased the paragraph font a little bit .
  assets/css/styles.css
  index.html
Labels: good first issue, hacktoberfest-accepted

#41 fix: align the download button to center
  assets/css/styles.css
  index.html
Labels: good first issue, hacktoberfest-accepted

#43 optimized website for mobile view.
  assets/css/styles.css
  index.html
Labels: enhancement, good first issue, hacktoberfest-accepted

#40 Remove the small image
  index.html
Labels: good first issue, hacktoberfest-accepted

#48 Added the class attribute for the img tag
  index.html
Labels: good first issue, hacktoberfest-accepted

#50 Added new class named "title" to the header and replaced the Bootstrap class "text-center" in the CSS stylesheet with "title" class .
  assets/css/styles.css
  index.html
Labels: good first issue, hacktoberfest-accepted

#52 Fixed the Download Icon inside the download button
  index.html
Labels: good first issue, hacktoberfest-accepted

#51 Added the div tag
  index.html
Labels: good first issue, hacktoberfest-accepted

#57 Completely Modified the README.md file into a new one
  README.md
  assets/img/Calculator_Img.jpg
Labels: enhancement, good first issue, hacktoberfest-accepted

#54 Size of the calculator is reduced
  assets/css/styles.css
Labels: good first issue, hacktoberfest-accepted

#59 Removed the .big-calculator class
  assets/css/styles.css
  index.html
Labels: good first issue, hacktoberfest-accepted

#63 Added a faint grey background to the paragraph that distinguishes its contents from the rest of the page.
  assets/css/styles.css
Labels: enhancement, good first issue, hacktoberfest-accepted

#64 Fixed the icon inside download button and removed the other button
  index.html
Labels: good first issue, hacktoberfest-accepted

#65 `Clone your forked repository` section and description are sticked together
  README.md
Labels: good first issue, hacktoberfest-accepted

#66 Added edo font in title
  assets/css/styles.css
Labels: enhancement, good first issue, hacktoberfest-accepted

#67 Changed paragraph margins
  assets/css/styles.css
Labels: good first issue, hacktoberfest-accepted

#72 Italic the heading
  .vscode/settings.json
  assets/css/styles.css
Labels: enhancement, good first issue, hacktoberfest-accepted

#74 Remove the "| YOSHITHA" part from the heading
  assets/css/styles.css
  index.html
Labels: good first issue, hacktoberfest-accepted

#73 bold and italic heading
  assets/css/styles.css
Labels: enhancement, good first issue, hacktoberfest-accepted

#84 Make the title margin 10px to 10vh
  assets/css/styles.css
Labels: enhancement, good first issue, hacktoberfest-accepted

#85 Changed the title of this page as required
  index.html
Labels: enhancement, good first issue, hacktoberfest-accepted

#88 Made the Heading Bold
  index.html
Labels: enhancement, good first issue, hacktoberfest-accepted

#91 Removed the bold from font style property in .title class of css file
  assets/css/styles.css
Labels: good first issue, hacktoberfest-accepted

#94 Reduced the background color of the pragraph
  assets/css/styles.css
Labels: good first issue, hacktoberfest-accepted

#39 added background image
  assets/css/styles.css
  index.html
Labels: enhancement, good first issue, hacktoberfest-accepted

#103 Changed the style of the page heading so as to make it stand out from the Page background .
  assets/css/styles.css
Labels: enhancement, good first issue, hacktoberfest-accepted

#107 Remove the background color of the paragraph
  assets/css/styles.css
Labels: enhancement, good first issue, hacktoberfest-accepted

#110 Changed heading color as required .
  assets/css/styles.css
Labels: enhancement, good first issue, hacktoberfest-accepted

#109 Increase the heading font size
  assets/css/styles.css
  index.html
Labels: enhancement, good first issue, hacktoberfest-accepted

#97 Changed the title of the page to CALCULATOR
  index.html
Labels: good first issue, hacktoberfest-accepted

#123 Removed the (ME) part from first sentence of README.md file
  README.md
Labels: good first issue, hacktoberfest

#124 Change the last sentence of the Contributing Section
  README.md
Labels: enhancement, good first issue, hacktoberfest

#125 Changed the link in the README.md file
  README.md
Labels: enhancement, good first issue, hacktoberfest

#127 Added python logo to the readme.md file
  README.md
Labels: enhancement, good first issue, hacktoberfest-accepted

#126 added blur effect to paragraph
  README.md
  assets/css/styles.css
Labels: enhancement, good first issue, hacktoberfest-accepted

#128 Made the download button text uppercase.
  index.html
Labels: enhancement, good first issue, hacktoberfest-accepted

#129 Changed the description a little bit.
  index.html
Labels: good first issue, hacktoberfest-accepted

#133 increase blur for paragraph background
  assets/css/styles.css
Labels: enhancement, good first issue, hacktoberfest-accepted

#132 changed paragraph background color
  assets/css/styles.css
Labels: enhancement, good first issue, hacktoberfest-accepted

#135 Removed doubled paragraph
  index.html
Labels: good first issue, hacktoberfest-accepted

#138 Download button from id to class
  assets/css/styles.css
  index.html
Labels: good first issue, hacktoberfest-accepted

#141 Added hover effect to the download button
  assets/css/styles.css
  index.html
Labels: enhancement, good first issue, hacktoberfest-accepted

#155 added js logo in readme.md file
  README.md
Labels: enhancement, good first issue, hacktoberfest-accepted

#160 Change readme title
  README.md
Labels: enhancement, good first issue, hacktoberfest-accepted

#156 Added the yaml logo to README file
  README.md
Labels: enhancement, good first issue, hacktoberfest-accepted

#139 Remove dash
  README.md
  index.html
Labels: good first issue, hacktoberfest-accepted

#140 Blur paragraph background
  assets/css/styles.css
Labels: enhancement, good first issue, hacktoberfest-accepted

#142 Update the Readme.md title
  README.md
Labels: enhancement, good first issue, hacktoberfest-accepted

#169 Change the sentence in readme.md file
  README.md
Labels: enhancement, good first issue, hacktoberfest-accepted

#172 Add yaml in used programming languages
  README.md
Labels: enhancement, good first issue, hacktoberfest

#170 Add python for the readme.md file
  README.md
Labels: enhancement, good first issue, hacktoberfest-accepted

#162 Add the Preview Link
  .github/pull_request_template.md
  .vscode/settings.json
Labels: enhancement, good first issue, hacktoberfest-accepted

#174 #173 repositioned visitor counter
  assets/css/styles.css
  index.html
Labels: enhancement, good first issue, hacktoberfest-accepted

#176 Adjust margin
  assets/css/styles.css
Labels: enhancement, good first issue, hacktoberfest-accepted

#181 Added img class and global css
  assets/css/styles.css
  index.html
Labels: enhancement, good first issue, hacktoberfest-accepted
